// src/types/answer/answer.tsx

export interface MWorksheet {
  worksheet_id: number; // integer, generated by default as identity, NOT NULL
  category_ty: number; // integer, NOT NULL
  title: string; // text, NOT NULL
  description?: string | null; // text, nullable
  thumbnail_url?: string | null; // text, nullable
  question_text: string; // text, NOT NULL
  start_at?: string | null; // timestamp with time zone, ISO8601文字列
  end_at?: string | null; // timestamp with time zone, ISO8601文字列
  is_active?: boolean | null; // boolean, default true
  sort?: number | null; // integer, default 0
  created_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
  updated_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
}

export interface MWorksheetAnswer {
  worksheet_id: number; // integer, NOT NULL
  no: number; // integer, generated by default as identity, NOT NULL
  answer_text: string; // text, NOT NULL
  sort?: number | null; // integer, default 0
  is_active?: boolean | null; // boolean, default true
  created_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
  updated_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
}

export interface TAnswer {
  answer_id: number; // integer, generated by default as identity, NOT NULL
  user_id: string; // uuid, NOT NULL
  worksheet_id: number; // integer, NOT NULL
  no: number; // integer, NOT NULL
  reason?: string | null; // text, nullable
  is_active?: boolean | null; // boolean, default true
  created_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
  updated_at?: string | null; // timestamp with time zone, ISO8601文字列, default now()
}
